services:
  python-demo-app:
    build:
      context: .
    container_name: python-demo-app
    env_file:
      - .env.example
    ports:
      - "8086:8080"
    volumes:
      - python-demo-app-data:/app/tmp/data

volumes:
  python-demo-app-data:

networks:
  default:
    name: moysklad-all_default
    external: true
